owncloud/encryption

lib/AppInfo/Application.php
lib/Command/MigrateKeys.php
lib/Command/SelectEncryptionType.php
lib/Controller/RecoveryController.php
lib/Controller/SettingsController.php
lib/Controller/StatusController.php
lib/Crypto/Crypt.php
lib/Crypto/DecryptAll.php
lib/Crypto/EncryptAll.php
lib/Crypto/Encryption.php
lib/Exceptions/PrivateKeyMissingException.php
lib/Exceptions/PublicKeyMissingException.php
lib/KeyManager.php
lib/Migration.php
lib/Recovery.php
lib/Session.php
templates/altmail.php
templates/mail.php
templates/settings-admin.php
templates/settings-personal.php

@DeepDiver1975 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/owncloud/encryption/

Scrutinizer Auto-Fixes

---

lib/Crypto/Encryption.php

Check if masterkey is enabled and return true.

Check if masterkey is enabled in isReadyForUser

---

.drone.yml
tests/bootstrap.php
tests/phpunit.xml

Boostrap testing of encryption app in drone

Init unit testing in drone

---

.drone.yml

Based on top of #30 - edit: which has been merged and this is now rebased on master
Initializes UI testing within drone

Bootstrap UI testing on drone

---

lib/AppInfo/Application.php
lib/Crypto/DecryptAll.php
tests/Crypto/DecryptAllTest.php

It should be able to read recovery password and oc
password from the env. This change helps to do the
same.

Provision to access recovery and oc password from env

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/apiEncryption/recreatemasterkey.feature
tests/acceptance/features/bootstrap/EncryptionContext.php
tests/acceptance/features/bootstrap/bootstrap.php

this steps & tests have been moved out of core in https://github.com/owncloud/core/pull/32354 and https://github.com/owncloud/core/pull/32361
now they need to be added and run here

run encryption specific api acceptance tests

---

.drone.yml

run all API tests from core with encryption app enabled

run api acceptance tests from core

---

lib/Crypto/EncryptAll.php
tests/Crypto/EncryptAllTest.php

When the files are already encrypted the
files need not be encrypted again.

Fix re-encrypting encrypted files

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/cliEncryption/recreatemasterkey.feature

Change inaccurate suite name from `apiEncryption`  to  `cliEncryption`
Locally tested

Change inaccurate suite name

---

.drone.yml
tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
tests/acceptance/features/lib/AdminEncryptionSettingsPage.php
tests/acceptance/features/webUIUserKeysType/userKeys.feature

Add skip on test scenario which is failing because of the issue below.
Related issue: #33
Add the missing drone setup for PR: #65

Add skip on failing test and add web ui suite on drone

---

.drone.yml

Added more tests to drone to remove the  tests from travis
related to #67

Add more tests to drone

---

tests/acceptance/features/bootstrap/EncryptionContext.php
tests/acceptance/features/cliEncryption/recreatemasterkey.feature
tests/acceptance/features/webUIUserKeysType/userKeys.feature

Adjust acceptance test step text changed in core

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/EncryptionContext.php

that was refactored recently in core

Add OccContext

---

Makefile
phpcs.xml
tests/acceptance/features/bootstrap/WebUIAdminEncryptionSettingsContext.php
vendor-bin/php_codesniffer/composer.json

Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.

Add php codesniffer

---

tests/acceptance/features/bootstrap/EncryptionContext.php
tests/acceptance/features/webUIUserKeysType/userKeys.feature

Unskip test for issue-33

---

composer.lock
tests/acceptance/features/bootstrap/EncryptionContext.php
tests/unit/Command/HSMDaemonTest.php
tests/unit/Command/RecreateMasterKeyTest.php
tests/unit/Command/TestEnableMasterKey.php
tests/unit/Command/TestEnableUserKey.php
tests/unit/Controller/RecoveryControllerTest.php
tests/unit/Controller/SettingsControllerTest.php
tests/unit/Controller/StatusControllerTest.php
tests/unit/Crypto/CryptHSMTest.php
tests/unit/Crypto/CryptTest.php
tests/unit/Crypto/DecryptAllTest.php
tests/unit/Crypto/EncryptAllTest.php
tests/unit/Crypto/EncryptionTest.php
tests/unit/Hooks/UserHooksTest.php
tests/unit/JWTTest.php
tests/unit/KeyManagerTest.php
tests/unit/MigrationTest.php
tests/unit/RecoveryTest.php
tests/unit/SessionTest.php
tests/unit/Users/SetupTest.php
tests/unit/UtilTest.php

1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)

Php unit 5 to 6

---

lib/Command/FixEncryptedVersion.php
lib/Command/HSMDaemon.php
lib/Command/RecreateMasterKey.php
lib/Crypto/DecryptAll.php
lib/KeyManager.php
tests/unit/Command/FixEncryptedVersionTest.php
tests/unit/Command/RecreateMasterKeyTest.php
tests/unit/Crypto/DecryptAllTest.php
tests/unit/Crypto/EncryptAllTest.php

Remove unused use statements

---

.drone.yml

1. show only usefull logs
the loglevel 0 does not help because most of the logs is cut away
This will also help to debug the current CI issues
2. split tests into more parts to be finished in <3h

improve CI

---

tests/unit/Command/FixEncryptedVersionTest.php

forward port of https://github.com/owncloud/core/pull/35288

do not disable encryption app after test run

---

tests/acceptance/features/webUIUserKeysType/userKeys.feature

Adjust create user test steps

---

.drone.yml

This test guarantee that the ```encryption``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611

encryption app test against latest tarball

---

Makefile

Added signing step to Makefile in order to unbundle and release the app individually

Added sign step to Makefile

---

.drone.starlark

These are starlark code enhancements that were added in activity app PR https://github.com/owncloud/activity/pull/802
Add them in encryption so it has up-to-date drone starlark code.
Note: this is starlark code only, which makes no difference to the generated `.drone.yml` here in the encryption app.

Extra scality and ceph flexibility in drone starlark

---

.drone.starlark
.drone.yml
phpunit.xml
tests/unit/Command/FixEncryptedVersionTest.php
tests/unit/Command/HSMDaemonTest.php
tests/unit/Command/RecreateMasterKeyTest.php
tests/unit/Command/TestEnableMasterKey.php
tests/unit/Command/TestEnableUserKey.php
tests/unit/Controller/RecoveryControllerTest.php
tests/unit/Controller/SettingsControllerTest.php
tests/unit/Controller/StatusControllerTest.php
tests/unit/Crypto/CryptHSMTest.php
tests/unit/Crypto/CryptTest.php
tests/unit/Crypto/DecryptAllTest.php
tests/unit/Crypto/EncryptAllTest.php
tests/unit/Crypto/EncryptionTest.php
tests/unit/Factory/EncDecAllFactoryTest.php
tests/unit/HookManagerTest.php
tests/unit/Hooks/UserHooksTest.php
tests/unit/JWTTest.php
tests/unit/KeyManagerTest.php
tests/unit/MigrationTest.php
tests/unit/Panels/AdminTest.php
tests/unit/Panels/PersonalTest.php
tests/unit/RecoveryTest.php
tests/unit/SessionTest.php
tests/unit/Users/SetupTest.php
tests/unit/UtilTest.php
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121

Adjust tests

---

.drone.starlark
.drone.yml

While running some tests on encryption I noticed that the API acceptance tests in drone give errors like:
https://drone.owncloud.com/owncloud/encryption/1027/36/11
```
{"reqId":"d3tUUgEA6xggvLuxAQbF","level":3,"time":"2019-12-10T00:25:59+00:00","remoteAddr":"172.22.0.7","user":"user0","app":"notifications","method":"POST","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","message":"Exception: {\"Exception\":\"Swift_TransportException\",\"Message\":\"Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:1025 (Connection refused)\",\"Code\":0,\"Trace\":\"#0 [internal function]: Swift_Transport_StreamBuffer->{closure}(2, 'stream_socket_c...', '\\\/var\\\/www\\\/ownclo...', 272, Array)\\n#1 …
```

API acceptance tests should have mailhog email available

---

.drone.starlark
tests/unit/Crypto/CryptHSMTest.php
tests/unit/Crypto/CryptTest.php
tests/unit/Crypto/DecryptAllTest.php
tests/unit/Crypto/EncryptAllTest.php
tests/unit/Crypto/EncryptionTest.php
tests/unit/KeyManagerTest.php
tests/unit/SessionTest.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`

Coding standard 2.0.0

---

.drone.starlark
.drone.yml

https://github.com/owncloud/QA/issues/640
Note: I have not switched this repo to starlark, because it gives `starlark: maximum file size exceeded`
See https://github.com/drone/drone-convert-starlark/pull/5 - the limit is currently 1 million bytes

Update starlark code 20200208

---

tests/unit/Command/FixEncryptedVersionTest.php
tests/unit/Panels/AdminTest.php
tests/unit/Panels/PersonalTest.php
vendor-bin/behat/composer.json

Part of https://github.com/owncloud/QA/issues/647

Implement phpunit v8

---

tests/acceptance/features/cliEncryption/recreatemasterkey.feature
tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
tests/acceptance/features/webUIUserKeysType/userKeys.feature

Similar to what was done in core recently.

Use realistic usernames

---

.drone.star
lib/AppInfo/Application.php
lib/Command/FixEncryptedVersion.php
lib/Command/HSMDaemon.php
lib/Command/MigrateKeys.php
lib/Command/RecreateMasterKey.php
lib/Command/SelectEncryptionType.php
lib/Controller/RecoveryController.php
lib/Crypto/Crypt.php
lib/Crypto/CryptHSM.php
lib/Crypto/DecryptAll.php
lib/Crypto/Encryption.php
lib/Hooks/UserHooks.php
lib/JWT.php
lib/KeyManager.php
lib/Migration.php
lib/Panels/Personal.php
lib/Recovery.php
lib/Session.php
lib/Users/Setup.php
lib/Util.php
phpstan.neon

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

.drone.starlark
.drone.yml

Issue https://github.com/owncloud/encryption/issues/238

[tests-only] Do not define SONAR_PULL_REQUEST env vars on nightly master CI

---

tests/acceptance/features/cliEncryption/recreatemasterkey.feature
tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
tests/acceptance/features/webUIUserKeysType/userKeys.feature

like was done in core last week.
Fixes CI - part of issue https://github.com/owncloud/QA/issues/653

[tests-only] Specify skeleton in tests

---

CHANGELOG.md
lib/Command/FixEncryptedVersion.php
tests/unit/Command/FixEncryptedVersionTest.php

Restore encrypted version to original if no fix was found

---

.drone.star

disable `csrf` to fix https://github.com/owncloud/encryption/issues/297

[CI] disable csrf to fix the failing tests

---

.drone.star
.drone/cancelBuilds.sh
Makefile
composer.json
composer.lock

https://github.com/owncloud/QA/issues/674
- Cancel Old running builds of a PR
**note** this PR was generated by a automated script
Added 2021-09-05: Update .drone.star and drop PHP 7.2
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687

[tests-Only][full-ci] Cancel Old running builds

---

.drone.star

[tests-only] [full-ci] Support download tests in .drone.star

---

.drone.star
vendor-bin/phan/composer.json

Part of https://github.com/owncloud/QA/issues/696

[tests-only] Bump PHP phan to major version 5

---

tests/acceptance/features/bootstrap/EncryptionContext.php
tests/acceptance/features/bootstrap/WebUIAdminEncryptionSettingsContext.php
tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/AdminEncryptionSettingsPage.php
tests/acceptance/features/lib/PersonalEncryptionSettingsPage.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

phpunit.xml

This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198

[tests-only][full-ci]Tidy up the phpunit xml file `encryption` app

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

merge back to master after release

Release 1.5.3

---

.drone.star
.gitignore

- it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
-  Applied other starlark changes waiting in activity app
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI

[full-ci]Use directory references and add some changes pending of activity app

---

tests/acceptance/features/apiEncryption/encoding.feature
tests/acceptance/features/cliEncryption/recreatemasterkey.feature
tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
tests/acceptance/features/webUIUserKeysType/userKeys.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:

[full-ci] [tests-only] Refactored inter scenarios space

---

composer.json
composer.lock
vendor-bin/phpstan/composer.json

Fixes #385 
Related issue https://github.com/phpstan/phpstan/issues/8938 was fixed in phpstan release 10.1.3

[tests-only] [full-ci] Use latest phpstan 1.10.3 or later

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back release branch. Github release only. Not publised on marketplace or portals now. Will be published with core 10.13.0
Closes #392

Release 1.6.0
