lib/Crypto/Encryption.php
This change is required so that move
operation executed by transer-ownership
command.
=> Change required for move operation

appinfo/Migrations/Version20170913113840.php, appinfo/info.xml
This change will help users to fix the migration
issue caused during upgrade to version 10. If
user had opted user specific key in the older versions
then no drop down will appear in the version 10.
Same applies if user had opted for the masterkey
in older version, no drop down will appear in version
10.
=> Fix migration issue caused during upgrade to version 10

lib/Hooks/UserHooks.php
This is to make sure that there are no user
specific folders if the keys are stored in
alternate location apart from the default
location, when a user is deleted. Hence the
keys inside user folder in the alternate
location would be deleted.
=> Cleanup alternate storage location keys of user

appinfo/info.xml, lib/Command/RecreateMasterKey.php, lib/Crypto/DecryptAll.php, lib/Crypto/EncryptAll.php, lib/KeyManager.php, tests/Command/RecreateMasterKeyTest.php, tests/KeyManagerTest.php
This change brings a new command to re-create
masterkey
=> Change to re-create masterkeys

lib/Command/RecreateMasterKey.php
logger is the last argument to DecryptAll which
was missing when DecryptAll is called. This change
fixes the same.
=> Fix the missing argument to DecryptAll

js/settings-admin.js
When recovery key is disabled after enabled
earlier, the password texts are cleared.
=> Clear text when recovery key is disabled

lib/Crypto/EncryptAll.php, tests/Crypto/EncryptAllTest.php
When dealing with copy and rename operation in
encryptall, its better to use '.part' appended
to the file name.
=> Use '.part' name appended to the file name for encryptall

lib/AppInfo/Application.php, lib/Hooks/UserHooks.php, tests/Hooks/UserHooksTest.php
Enable user-keys if no encryption mode is enabled
during user login.
=> Enable user-keys if no encryption mode is enabled during login

lib/AppInfo/Application.php, lib/Crypto/DecryptAll.php, tests/Crypto/DecryptAllTest.php
When the decryptall is called with user-keys
enabled, make sure the password provided by
user is correct else throw exception.
=> Fix login exception in decryptall

lib/Hooks/UserHooks.php, tests/Hooks/UserHooksTest.php
When user tries to set the password without logging
in for once and no session available, the user-keys
encryption was failing to create the private key
for the new password. This change helps to fix the
issue.
=> Fix user-keys encryption when user created with email

.drone.yml
``TEST_SOURCE: encryption`` was a NOOP - there is no pipeline step that matches it. The 2 matrix entries here were just doing all the setup and then exiting "happy". Actually there are no specific ``api`` acceptance tests in the encryption app.
Change these matrix entries so they run the ``cli`` acceptance tests, like the matrix entry above them.
=> Run cli acceptance tests for pgsql and PHP 7.2

tests/unit/Crypto/DecryptAllTest.php, tests/unit/Crypto/EncryptAllTest.php
Use unique usernames in unit tests.
=> Use unique usernames in unit tests

.drone.yml
The UI core stable10 with masterkey encryption drone matrix section was only running 12 of 15 parts of the core webUI test suites. Matrix jobs for parts 13,14,15 were missed.
I noticed this while comparing drone here with user_ldap and files_primary_s3 that also do this sort of thing.
=> Run all 15 parts of core webUI test suites

Makefile
To use the now-standard way that the help information is formatted into columns.
(taken from examples now in other app repos)
Do this easy thing before other changes coming for issue #81
=> Adjust 'make help' output

.drone.yml, Makefile
1) push the "gory" details of the ``run.sh`` command for running core acceptance tests down from drone to ``Makefile``
2) In the ``run.sh`` command specify how to find the core Behat config, and what combination of tags to select. That will make hose things "fixed" for anyone who calls the ``Makefile`` target.
3) Leave the control of how many parts (jobs) to parallel ( ``DIVIDE_INTO_NUM_PARTS`` and ``RUN_PART`` ) in drone. That is a performance/elapsed time thing that we are controlling for drone. If someone else wants to ``make test-acceptance-core-api`` or ``make test-acceptance-core-webui`` then they will need to decide for themselves if they are running all test scenarios matching the tags (hours of run time), or defining a "part" to run, or they might want to define ``BEHAT_SUITE`` …
=> Refactor running core acceptance tests

.drone.yml, Makefile
We are using owncloud-coding-standard to effectively provide PHP syntax (lint) checks these days.
So remove ``lint`` from here, and run owncloud-coding-standard for each PHP version.
Note: ``encryption`` app is currently for use with core ``master`` and so only needs PHP 7.1 and later.
=> Use owncloud-coding-standard for PHP lint syntax checks

appinfo/info.xml, lib/AppInfo/Application.php, lib/Command/HSMDaemon.php, lib/Crypto/Crypt.php, lib/Crypto/CryptHSM.php, lib/Hooks/UserHooks.php, lib/JWT.php, lib/KeyManager.php, lib/Recovery.php, lib/Users/Setup.php, tests/unit/Command/HSMDaemonTest.php, tests/unit/Crypto/CryptHSMTest.php, tests/unit/JWTTest.php
Integrate HSM changes to encryption
=> Integrate HSM changes to encryption

tests/acceptance/features/bootstrap/EncryptionContext.php
the testing app does not trim the content any more (see owncloud/testing#90), so we don't want to trim it on the receiver side
=> do not trim content of downloaded file

lib/Command/RecreateMasterKey.php, tests/unit/Command/RecreateMasterKeyTest.php
After the command is executed successfully by
recreating masterkey, the user should be informed
to relogin.
=> Add re-login information after successful action

.drone.yml, tests/unit/Command/RecreateMasterKeyTest.php
core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698
and cherry-pick from #107 "Fix unit test for RecreateMasterkey" because this is also an outstanding item in order to get green CI.
=> Drop php 5.6

appinfo/info.xml, vendor-bin/behat/composer.json
because the app is now being tested only against core `stable10` upcoming `10.2` that has dropped PHP 5.6 support.
Note: the root `composer.json` in this repo already says PHP 7.1 - so we can do that for `behat` also.
If someone some day wants to backport this separated repo stuff to be in core `stable10` (before core `stable10` has dropped PHP 7.0 support) then they anyway have to sort out retrofitting PHP 7.0 support.
=> Adjust composer files and app core min-version for 'drop PHP 5.6'

tests/acceptance/features/cliEncryption/recreatemasterkey.feature, tests/acceptance/features/webUIUserKeysType/userKeys.feature
Apply a couple of minor differences that are in core `stable10`
Having the matching tags will not hurt anything, and will get rid of the annoying line when doing diffs.
See core PR https://github.com/owncloud/core/pull/34770 for code going the other way
=> Sync test code from core

phpunit.xml, tests/unit/Hooks/UserHooksTest.php
These days `phpunit` warns about "risky" tests, like ones that do not make any assertions. For example, these can be tests that check that something "works" - the real method call does not throw an exception. And if the real method call "returns void" on success, then there is nothing much to assert. phpunit will already "built in by default" "assert" that no exception happens.
It is nice to know about such unit tests. Then examine what they do.
1) If they are actually snake oil, then fix them up so that they test something real; or
2) If they really just have to expect that the method "returns void" and no exception is thrown, then wrap the method call in `assertNull()` to check that we get out of the method and "nothing"  is returned.
In the 2nd commit fixup the "risky" unit tests.
=> Enable failOnRisky for phpunit tests

appinfo/info.xml, lib/Command/FixEncryptedVersion.php, tests/unit/Command/FixEncryptedVersionTest.php, tests/unit/Hooks/UserHooksTest.php
Add a new command to fix the encryption
version. This would help the admin to
fix the issues related to encryption version
mismatch for the files.
=> Add encryption version fix command

tests/unit/Command/FixEncryptedVersionTest.php
I really did this to demonstrate the other CI issues we had yesterday. Now the QA tarball problems are corrected and CI passes. We may as well fix this typo.
Backport to core `stable10` is in https://github.com/owncloud/core/pull/35000
=> Fix minor typo in FixEncryptedVersionTest

tests/unit/Command/FixEncryptedVersionTest.php
Its better to verify if the command output contains specific
strings, instead of grabbing the whole command output and
comparing with string equal.
=> Fixing encrypted version test

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
Add acceptence test to check that user have to relog in in order to access their files after the administrator has recreated the master key in encryption.
Fixes #123 
~~Note: This requires https://github.com/owncloud/core/pull/35246 to be merged first~~
=> Add acceptance test for checking file access after recreating master key in encryption

lib/Command/RecreateMasterKey.php, lib/Crypto/EncryptAll.php, lib/Factory/EncDecAllFactory.php, lib/Util.php, tests/unit/Command/RecreateMasterKeyTest.php, tests/unit/Crypto/EncryptAllTest.php, tests/unit/Factory/EncDecAllFactoryTest.php, tests/unit/UtilTest.php
Fix recreate masterkey for hsm
=> Fix recreate masterkey for hsm

tests/acceptance/features/cliEncryption/recreatemasterkey.feature, tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
that changed in core https://github.com/owncloud/core/pull/35438
=> Adjust create user steps

tests/acceptance/features/webUIUserKeysType/userKeys.feature
Encryption issue #33 was fixed in core `master` by https://github.com/owncloud/core/pull/35575
Now that we have up-to-date QA tarballs of core, we notice that the related acceptance test here in the `encryption` app needs to be adjusted.
=> Issue 33 has been fixed in core - adjust the encryption repo acceptance test

.drone.yml
The acceptance test `run.sh` output was saying stuff like:
```
Running webUIUserKeysType tests tagged ~@skipWhenTestingRemoteSystems&&~@skipOnOcV10&&~@skipOnOcV10.3&&~@skipOnOcV10.3.0&&~@skipOnEncryption&&~@skipOnEncryptionType:&&~@skip&&@webUI on browser 'chrome' on platform 'Linux'
```
The actual encryption type was missing from `~@skipOnEncryptionType:` - it should say `~@skipOnEncryptionType:user-keys` or `~@skipOnEncryptionType:masterkey`
=> Specify ENCRYPTION_TYPE var when running core tests

CHANGELOG.md, Makefile, appinfo/info.xml
Update changelog to reflect changes in 1.4.0 ( these are the changes from owncloud [10.2.1](https://github.com/owncloud/core/commits/v10.2.1/apps/encryption) to [10.3](https://github.com/owncloud/core/commits/45a5d8faa20eda4ae4c09e44e477001787dcfe19/apps/encryption) )
=> Add changelog for 1.4.0

.drone.yml
because some pairs of acceptance test suites are taking a long time to run.
e.g. `apiShareManagementBasic` and `apiShareOperations` were running in the same job and taking close to 4 hours to finish.
(I will review all this again as I do the drone starlark conversion, but for now let's get the elapsed test time down)
- test with core latest release and 10.3.0RC1
=> Split core acceptance tests into 25 parts

.drone.starlark, .drone.yml, Makefile
And reduce the number of parts that the core API tests are split into.
Because there is currently a limit of 1,000,000 bytes on the size of .drone.yml
Beacuse of issue https://github.com/owncloud/user_ldap/issues/509
( `user_ldap` was already running some core CLI acceptance tests with both LDAP and encryption together, so be had better run core CLI acceptance tests with encryption here)
=> Run core CLI acceptance tests in drone

vendor-bin/phpstan/composer.json
without actually enabling it.
Issue https://github.com/owncloud/QA/issues/642
Note: PR #189 attempts to enable `phpstan` here, but that is taking more effort to sort out the things that `phpstan` finds.
=> Bump phpstan to 0.12

phpstan.neon
- adjust `phpstan.neon` for new `bootstrapFiles` section.
- remove Migrations from `excludes_analyse` section, they can be analyzed OK now
=> Adjust phpstan.neon

tests/acceptance/features/webUIUserKeysType/userKeys.feature
Getting all share details of a sharer when receiver already has a file with the matching name
https://github.com/owncloud/encryption/issues/206
=> [Tests-Only] Add acceptance test to get all shares of a sharer when the receiver already has a file that matches shared file name

lib/Crypto/Crypt.php
https://github.com/phpstan/phpstan/releases/tag/0.12.31 fixed its definition of the signature of `openssl_pkey_export` PR https://github.com/phpstan/phpstan-src/pull/256
`phpstan` started reporting:
https://drone.owncloud.com/owncloud/encryption/1324/4/4
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
------ --------------------------------------------- 
Line   lib/Crypto/Crypt.php                         
------ --------------------------------------------- 
119    No error to ignore is reported on line 119.  
------ --------------------------------------------- 
[ERROR] Found 1 error 
```
Remove `phpstan-ignore-line`
=> [Tests-Only] Remove unneeded phpstan-ignore-line for openssl_pkey_export

lib/Crypto/Crypt.php
In certain constellations, e.g. file version 1 and block position 10 or file version 11 and block position 0, the mac could collide. To prevent this I introduce a seperator between the file version and the block position.
=> fix: avoid mac collisions

.drone.star, appinfo/info.xml, composer.lock, vendor-bin/behat/composer.json
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
And adjusting owncloud min-version="10.3" because we want to ensure PHP 7.1 and... - it would require a bunch of extra testing to ensure that we could run the latest encryption app code with ownCloud 10.2 and PHP 7.0
=> Adjust PHP dependencies for composer 2.0

lib/Command/FixEncryptedVersion.php, tests/unit/Command/FixEncryptedVersionTest.php
Part of https://github.com/owncloud/enterprise/issues/4276
- Previously, `FixEncryptedVersion` command only can be run for all the files of user. This pr adds `path` option to `FixEncryptedVersion` command to limit files to fix.
- If path indicates a file, only the file will be fixed. If indicates a directory, all the files inside directory will be fixed by command. 
- If path option exist, the user is determined by the path and the user parameter is ignored.
=> add path option to FixEncryptedVersion command

lib/Command/FixEncryptedVersion.php, tests/unit/Command/FixEncryptedVersionTest.php
While running the command  encryption:fix-encrypted-version binary data has been printed, this PR fixed this.
Before:
After:
=> Prevent command encryption:fix-encrypted-version from printing file binary data

lib/Crypto/Crypt.php, vendor-bin/behat/composer.json
1) Pin the version of `Behat/Gherkin` to avoid issue https://github.com/Behat/Gherkin/issues/187
2) phpstan 0.12.69 https://github.com/phpstan/phpstan/releases/tag/0.12.69 was released yesterday. That fixed a code analysis error about `OPENSSL_VERSION_NUMBER` constant. Remove the `phpstan-ignore-line` annotation.
workaround for #38338
=> [tests-only] Pin behat/gherkin because of Gherkin issue 187

.drone.starlark, .drone.yml, lib/Crypto/Crypt.php, lib/Crypto/CryptHSM.php, lib/Crypto/Encryption.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiEncryption/encoding.feature, tests/unit/Crypto/CryptTest.php
Fixes #210, https://github.com/owncloud/core/issues/10831
Needs https://github.com/owncloud/core/pull/38249
This PR makes binary encoding default and writes the encoding info to the file metadata. After this PR, all the newly created files will be encrypted with binary encoding.
For decryption, if no metadata presents we keep continue to decrypt these files with legacy base64 encoding, if header is present we use binary encoding to decrypt those files.
=> allow binary encoding for written files to reduce file size

.drone.starlark, .drone.yml
This reverts commit 3f84a18068d5a90651ba9da95cd184afb8dd2f59.
Now that 10.7.0 is "latest" we should be able to test against "latest" again.
=> [tests-only] Revert "Do not test against latest (10.6.0)"

CHANGELOG.md, lib/Crypto/CryptHSM.php
This caused issues migrating HSM instances with encryption to 10.7
Fixes #269
=> Use binary encoding setting for HSM

README.md
I am always confused, when the readme points to a wrong CI instance. In this case its is obviously outdated: 3 years no activity on travis -> we can safely switch.
=> Switch CI badge from travis to drone

lib/KeyManager.php
Fixes #295 
`$encryptedFileKey` is always not-false at this point in the code, because there is an earlier test for if it is `empty()` which returns early.
`phpstan` worked this out, an complained. See the issue.
Remove the useless part of the `if` test.
=> Remove always-true encryptedFileKey var from if test

.drone.star, phpunit.xml, sonar-project.properties, tests/unit/Command/TestEnableMasterKey.php, tests/unit/Command/TestEnableUserKey.php, tests/unit/Controller/SettingsControllerTest.php, tests/unit/Crypto/EncryptAllTest.php, tests/unit/KeyManagerTest.php, vendor-bin/behat/composer.json
Fixes #306 
1) switch to using PHP 7.4 for PHP unit tests with coverage (there is sometimes a problem generating coverage with PHPunit9 and PHP 7.3 and something in our combinations of dependencies... - we can easily avoid that, PHP 7.3 is about to end security support anyway...)
2) Migrate `phpunit.xml` with the command:
`../../lib/composer/bin/phpunit --migrate-configuration`
3) use phpunit 9 in acceptance test dependencies. That will fix failures running core tests like:
https://drone.owncloud.com/owncloud/encryption/2104/44/16
```
Fatal error: Call to undefined method PHPUnit\Framework\Assert::assertMatchesRegularExpression() (Behat\Testwork\Call\Exception\FatalThrowableError)
```
=> [tests-only] [full-ci] Bump tests to phpunit9

.drone.star
because of https://github.com/owncloud/encryption/issues/315 some tests fail with latest, so run them with 10.9.1RC1
this PR needs to be reverted after 10.9.1 is released and updated if there is an other RC
=> run tests with 10.9.1RC1 instead of master

.drone.star
same as #316 but for a last suite
this suite only runs nightly, that is why #316 did not fail
=> run webUI core tests not on latest but on 10.9.1RC1

.drone.star
10.9.1RC2 tarballs are now available, so use them.
Note: many of the pipelines run in nightly CI. So this needs to be merged, and we will get results overnight.
=> [tests-only] [full-ci] Test against 10.9.1RC2

.drone.star
Part of issue #317 
I reverted the 3 commits from PRs #322 #318 #316 in reverse order:
```
$ git checkout -b test-against-core-latest
Switched to a new branch 'test-against-core-latest'
$ git revert 398bf2a20c4dd1a94adb5dcf097b1e30766d5674
[test-against-core-latest 211ad06] Revert "Test against 10.9.1RC2"
1 file changed, 7 insertions(+), 7 deletions(-)
$ git revert 05d8975a18631a2d60a63691a577a2c9af3753f0
[test-against-core-latest f928a77] Revert "run webUI core tests not on latest but on 10.9.1RC1"
1 file changed, 2 insertions(+), 2 deletions(-)
$ git revert dc59932798a0b228d9502be2a64aa136492dc952
[test-against-core-latest 408530c] Revert "run tests with 10.9.1RC1 instead of master"
1 file changed, 6 insertions(+), 6 deletions(-)
```
=> [tests-only] Test against core latest

tests/acceptance/features/apiEncryption/quotaOc10Issue40140.feature
Added bug demonstration tests for quota
Closes https://github.com/owncloud/encryption/issues/345
=> [tests-only] Added bug demonstration quota tests

tests/unit/Crypto/CryptHSMTest.php
Fixes #347 
The errors reported were:
```
$ make test-php-unit NOCOVERAGE=true
php -d zend.enable_gc=0 ../../lib/composer/bin/phpunit --configuration ./phpunit.xml --testsuite unit
PHPUnit 9.5.21 #StandWithUkraine
Runtime:       PHP 7.4.30
Configuration: ./phpunit.xml
Warning:       No code coverage driver available
.......................................E..EE...................  63 / 259 ( 24%)
............................................................... 126 / 259 ( 48%)
............................................................... 189 / 259 ( 72%)
............................................................... 252 / 259 ( 97%)
.......                                                         259 / 259 (100%)
Time: 00:46.756, Memory: 40.00 MB
There were 3 errors:
1) …
```
=> [tests-only] [full-ci] Fix PHP unit tests for GuzzleHttp

lib/Crypto/Crypt.php
fixes decryption errors when a block happens to be of length 1 and be `"0"`
can be testet with a file containing just "0" or a file containing 6073 "0":
```
for f in `seq 0 6072` ; do echo -n "0" >> 6073.bin ; done
```
=> use typesafe comparison

lib/Crypto/Encryption.php, tests/unit/Crypto/EncryptionTest.php
`files:checksum:verify` was failing due to problems finding the right key with the versions that were in the trashbin. This was caused by a wrong computation for the right path where the key is.
Rel https://github.com/owncloud/enterprise/issues/5272
=> Handle the versions in the trashbin for the checksum verify command

tests/acceptance/features/bootstrap/EncryptionContext.php
Refactored the method name from `readFileInServerRoot` to `readFileInServerRootForCore` as changed in core.
- Fixes https://github.com/owncloud/QA/issues/755
=> [full-ci] [tests-only] Fixed the method name changed recently in core

tests/acceptance/features/bootstrap/EncryptionContext.php
The PR https://github.com/owncloud/core/pull/40359 has implemented different method to save the exitcode of the last occ command and the local tests were failing because the exitcode was not saved.
In this PR, I have implemented the updated way to save the occ exitCode.
Fixes https://github.com/owncloud/encryption/issues/369
=> [tests-only] Save exitcode of last occ command

tests/acceptance/expected-failures-cli.md
The line number was changed here recently: https://github.com/owncloud/core/pull/40435/files
Closes https://github.com/owncloud/encryption/issues/373
=> [tests-only] Update expected failure line number

.drone.star, appinfo/Migrations/Version20170913113840.php, appinfo/routes.php, lib/AppInfo/Application.php, lib/Command/RecreateMasterKey.php, lib/Crypto/Crypt.php, lib/Crypto/CryptHSM.php, lib/Crypto/DecryptAll.php, lib/Crypto/EncryptAll.php, lib/Hooks/UserHooks.php, lib/Migration.php, lib/Session.php, vendor-bin/phan/composer.json
`phan` will report errors if any of the code is not compatible with PHP 7.3.
This app still supports PHP 7.3 when used with oC10 core 10.11 and earlier.
To get `phan` passing, I suppressed most of the things it reported. They all look like OK code to me, just deprecated calls, and some code idioms that phan thinks are a bit odd.
=> [tests-only] [full-ci] Run phan with PHP 7.3

README.md
I had a hard time yesterday trying to find out why I was getting `503` with the message 
`Encryption not ready: multikeyencryption failed error:0480006C:PEM routines::no start line` and later on found out that the encryption was not supported in my ubuntu 22 as it has openssl v3. While it's mentioned here https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#openssl-version
I think it's relevant to mention it in the readme as well.
=> [docs-only] Update readme to metion that encryption is supported only on oppenssl v1

vendor-bin/behat/composer.json
Due to changes in core with this PR https://github.com/owncloud/core/pull/40619. Certain Apps requires to have a package `json-assertion` which was added in core. This PR adds the required package.
https://github.com/owncloud/QA/issues/800
=> [tests-only][full-ci]Added `json-assert` library to `encryption` app

vendor-bin/phpstan/composer.json
Related issue #385 
If we do not get any other fix quickly, we can pin phpstan to 1.9.18 (the version yesterday that passes)
=> Pin phpstan to 1.9.18

tests/unit/Crypto/EncryptAllTest.php
In preparation of php8.2 support - see https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
Similar to core https://github.com/owncloud/core/pull/40995
=> [tests-only] fix: drop usage of ${}

.drone.star
This PR change the rocketchat notification server `chat` to `talk`.
Part of https://github.com/owncloud/QA/issues/846
=> [tests-only] Changed rocketchat notifications server  to 
